### ISSUE TITLE
tutorial collection as errors

### ISSUE THREAD

**Issue by erixtekila** [marionettejs/guides#13]
There is a typo in the `driver.js` code

```js
initialize: function() {
    this.collection = new Backbone.Collection([
      {assignee: 'Scott', text: 'Write a book about Marionette'},
      {assignee: 'Andrew', text: 'Do some coding'}//<--- watch out the colon, instead of the comma
    ]);
  }
```

**Comment by scott-w** [comment]
Cheers @erixtekila 

I've just checked and this has been subsequently fixed at https://github.com/marionettejs/guides/blob/master/en/appendix/getting_started/tutorial/todo_app.md

Could we close this ticket please @jdaudier

**Comment by jdaudier** [comment]
Thanks all!
