### ISSUE TITLE
itemAdded never gets called

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/guides#16]
> Now, whenever we click on the "Add Item" button, a new job will be added to our todo list and the form will be cleared. We've taken an opportunity to introduce model and collection driven events as well. For a full list of events, see the Backbone documentation.

**itemAdded never gets called**

submitted by: @pelachile on https://www.gitbook.com/book/marionette/marionette-guides/discussions/3

**Comment by scott-w** [comment]
Thanks for this, I'll look into it as soon as possible.
