### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by scott-w** [marionettejs/guides#25]
While it should be obvious that readers could copy and paste code, we should include an explicit license grant in the text to provide that extra confidence.

With that in mind, the choices would be:
- MIT
- 2 or 3 clause BSD
- Public Domain grant
- CC0 license (current)

Are there any preferences?

**Comment by jdaudier** [comment]
I like MIT

**Comment by scott-w** [comment]
I've just checked and there's a CC0 license applied to everything. I'll do some research to see if that's a good enough license. If it is, we can just reference it at the start of the book.

**Comment by scott-w** [comment]
The CC0 License is appropriate for software
