### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/guides#34]
> We'll be using the layout described in the introduction, so let's move the bulk of our view code into views/layout.js and rejig it a little:

```
bundle.js:17800 Uncaught Error: Cannot find module "../models/todo"
```

models are not defined in this or prior sections in the tutorial

/cc @scott-w 

submitted by @iampeterbanjo

**Comment by iampeterbanjo** [comment]
Sorry this was my mistake - I missed a part in the previous step in which the model was created.
