### ISSUE TITLE
The 'Marionette.LayoutView' is not working in marionette v3.0.0

### ISSUE THREAD

**Issue by simudin91** [marionettejs/guides#39]
I tried the tutorial with marionette 3.0.0 and the The 'Marionette.LayoutView' is not working anymore.
I changed it to 'Marionette.View' and it's working.

**Comment by scott-w** [comment]
Hi @simudin91,

The guides currently only cover Marionette 2. We're still updating the documentation for Mn 3 then we'll be in a position to start updating the guides.
